run:
  mode: 'train'
  device: 'gpu'
transforms: none
dataset:
  class_name: "ISIC2018Dataset"
  input_size: 224
  training:
    params:
      data_dir: "/path/to/datasets/ISIC2018"
  validation:
    params:
      data_dir: "/path/to/datasets/ISIC2018"
  number_classes: 2
data_loader:
  train: 
    batch_size: 16
    shuffle: true
    num_workers: 8
    pin_memory: true
  validation: 
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
  test:
    batch_size: 16
    shuffle: false
    num_workers: 4
    pin_memory: false
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0001
  criterion:
    name: "DiceLoss"
    params: {}
  scheduler:
    factor: 0.5
    patience: 10
  epochs: 100
model:
  save_dir: '../../saved_models/isic2018_transunet'
  load_weights: false
  name: 'VisionTransformer'
  params:
    img_size: 224
    num_classes: 2
# preprocess: